### ISSUE TITLE
Write testing cases for task3

### ISSUE THREAD

**Issue by rwu5** [YongjianZhu/expertiza#11]

**Comment by Yolanda-Ling-Li** [comment]
1. Couldn't find appropriate test file of user list. The code of testing issue 3 is written in spec/features/list_teams_spec.rb

2. Couldn't receive data from database. Then we find that when we run test file, the data in expertiza_test are cleared, but we still can grab data from website. It seems that while running test, the view will get data from expertiza_development rather than expertiza_test.

**Comment by Yolanda-Ling-Li** [comment]
3. Add "create user" part before test part. Find that new create user will be saved in expertiza_test database. However, data grabed from website doesn't include those new create user.
